name=tiny32_v5
version=3.18.2
author=tenergyinnovation <fb: www.facebook.com/tenergyinnovation>
maintainer=tenergyinnovation <fb: www.facebook.com/tenergyinnovation>
sentence=A library for tiny32_v5
paragraph=tiny32_v5 library
category=Communication
url=https://github.com/tenergyinnovation/tiny32_v5
architectures=esp32,tiny32
